import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/components/utils/NextAuthProvider";
import MuiThemeProvider from "@/components/utils/MuiThemeProvider";
import { primary } from "@/utils/theme/palette";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;

}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <MuiThemeProvider customTheme={primary}>
            {children}
          </MuiThemeProvider>
        </NextAuthProvider>
        </body>
    </html>
  );
}
